// Ravi's Tuition — Data (AglaSem copy base + new features)
// Brand exact per 05, catalogue ingest from 04_catalogue.json (16 live), validation, quarantine, real webp tiles
window.SITE_DATA = {
  brand: {
    name: "Ravi's Tuition",
    tagline: "MADURAI · SINCE 1999",
    line: "Ravi's Tuition · ravistuition.in | 86106 53352",
    primary: "#17528C",
    classes: [8,9,10,11,12],
    subjects: {
      8: ["tamil","english","maths","science","social"],
      9: ["tamil","english","maths","science","social"],
      10: ["tamil","english","maths","science","social"],
      11: ["tamil","english","maths","physics","chemistry","biology","computer-science","commerce","accountancy","economics"],
      12: ["tamil","english","maths","physics","chemistry","biology","computer-science","commerce","accountancy","economics"]
    },
    subjectMeta: {
      "tamil": {"en":"Tamil","ta":"தமிழ்"},
      "english": {"en":"English","ta":"ஆங்கிலம்"},
      "maths": {"en":"Maths","ta":"கணிதம்"},
      "science": {"en":"Science","ta":"அறிவியல்"},
      "social": {"en":"Social Science","ta":"சமூக அறிவியல்"},
      "physics": {"en":"Physics","ta":"இயற்பியல்"},
      "chemistry": {"en":"Chemistry","ta":"வேதியியல்"},
      "biology": {"en":"Biology","ta":"உயிரியல்"},
      "computer-science": {"en":"Computer Science","ta":"கணினி அறிவியல்"},
      "commerce": {"en":"Commerce","ta":"வணிகவியல்"},
      "accountancy": {"en":"Accountancy","ta":"கணக்குப்பதிவியல்"},
      "economics": {"en":"Economics","ta":"பொருளாதாரம்"}
    }
  },
  // Live catalogue — 16 records from 04_catalogue.json, field names fixed contract per 02
  resources: [
    {
      "id": "10-maths-english-quarterlyimpq-2026",
      "title_en": "10th Maths Quarterly Important Questions 2026 - English Medium",
      "title_ta": "10 ஆம் வகுப்பு கணிதம் காலாண்டு முக்கிய வினாக்கள் 2026",
      "class": 10,
      "subject": "maths",
      "medium": "English",
      "exam_type": "Quarterly",
      "resource_type": "Important-Q",
      "year": 2026,
      "pages": 12,
      "price_tier": "free",
      "price_inr": 0,
      "marks_pattern": "Part I 14×1=14 · Part II 10×2=20 (Q.28 compulsory) · Part III 10×5=50 · Part IV 2×8=16 = 100 marks, 3.00 hrs",
      "file_url": "s3://ravis-tuition/10-maths-quarterly-2026.pdf",
      "is_free_lead_magnet": true,
      "has_real_tile": true
    },
    {
      "id": "10-science-english-quarterlyimpq-2026",
      "title_en": "10th Science Quarterly Important Questions 2026 - FREE Sample",
      "title_ta": "10 ஆம் வகுப்பு அறிவியல் காலாண்டு முக்கிய வினாக்கள் 2026",
      "class": 10,
      "subject": "science",
      "medium": "English",
      "exam_type": "Quarterly",
      "resource_type": "Important-Q",
      "year": 2026,
      "pages": 10,
      "price_tier": "free",
      "price_inr": 0,
      "marks_pattern": "Physics 25 + Chemistry 25 + Biology 50 = 100 marks, 3 hrs",
      "file_url": "s3://ravis-tuition/10-science-2026.pdf",
      "is_free_lead_magnet": true,
      "has_real_tile": true
    },
    {
      "id": "12-physics-english-quarterlyimpq-2026",
      "title_en": "12th Physics Quarterly Important Questions 2026",
      "title_ta": "12 ஆம் வகுப்பு இயற்பியல் காலாண்டு முக்கிய வினாக்கள் 2026",
      "class": 12,
      "subject": "physics",
      "medium": "English",
      "exam_type": "Quarterly",
      "resource_type": "Important-Q",
      "year": 2026,
      "pages": 14,
      "price_tier": "free",
      "price_inr": 0,
      "marks_pattern": "Part I 15×1 · Part II 6×2=12 · Part III 6×3=18 · Part IV 5×5=25 = 70 marks, 3.00 hrs",
      "file_url": "s3://ravis-tuition/12-physics-2026.pdf",
      "has_real_tile": true
    },
    {
      "id": "12-chemistry-english-quarterlyimpq-2026",
      "title_en": "12th Chemistry Quarterly Important Questions 2026 + Reactions Bank",
      "title_ta": "12 ஆம் வகுப்பு வேதியியல் காலாண்டு முக்கிய வினாக்கள் 2026",
      "class": 12,
      "subject": "chemistry",
      "medium": "English",
      "exam_type": "Quarterly",
      "resource_type": "Important-Q",
      "year": 2026,
      "pages": 16,
      "price_tier": "free",
      "price_inr": 0,
      "marks_pattern": "Part I 15×1 · Part II 6×2 · Part III 6×3 · Part IV 5×5 = 70 marks",
      "file_url": "s3://ravis-tuition/12-chemistry-2026.pdf",
      "has_real_tile": true
    },
    {
      "id": "10-maths-english-halfyearlymodel-2025",
      "title_en": "10th Maths Half-Yearly Model Paper 2025",
      "title_ta": "10 ஆம் வகுப்பு கணிதம் அரையாண்டு மாதிரி 2025",
      "class": 10,
      "subject": "maths",
      "medium": "English",
      "exam_type": "Half-Yearly",
      "resource_type": "Model Papers",
      "year": 2025,
      "pages": 8,
      "price_tier": "free",
      "price_inr": 0,
      "marks_pattern": "Part I 14×1 · Part II 10×2 (Q.28 compulsory) · Part III 10×5 · Part IV 2×8 = 100 marks",
      "file_url": "s3://ravis-tuition/10-maths-half-2025.pdf"
    },
    {
      "id": "10-maths-english-annualanswerkey-2025",
      "title_en": "10th Maths Annual Answer Key 2025 - Marking Scheme",
      "title_ta": "10 ஆம் வகுப்பு கணிதம் விடைக்குறிப்பு 2025",
      "class": 10,
      "subject": "maths",
      "medium": "English",
      "exam_type": "Annual",
      "resource_type": "Answer Keys",
      "year": 2025,
      "pages": 18,
      "price_tier": "free",
      "price_inr": 0,
      "marks_pattern": "Full marking scheme with step marks",
      "file_url": "s3://ravis-tuition/10-maths-key-2025.pdf"
    },
    {
      "id": "12-physics-english-publicpyq-2024",
      "title_en": "12th Physics Public Exam PYQ 2024 - Original Paper",
      "title_ta": "12 ஆம் வகுப்பு இயற்பியல் பொதுத்தேர்வு 2024",
      "class": 12,
      "subject": "physics",
      "medium": "English",
      "exam_type": "Public",
      "resource_type": "PYQ",
      "year": 2024,
      "pages": 6,
      "price_tier": "free",
      "price_inr": 0,
      "marks_pattern": "Part I 15×1 · Part II 6×2 · Part III 6×3 · Part IV 5×5 = 70 marks",
      "file_url": "s3://ravis-tuition/12-physics-2024.pdf"
    },
    {
      "id": "10-tamil-tamil-quarterlyimpq-2026",
      "title_en": "10th Tamil Quarterly Important Questions 2026",
      "title_ta": "10 ஆம் வகுப்பு தமிழ் காலாண்டு முக்கிய வினாக்கள் 2026",
      "class": 10,
      "subject": "tamil",
      "medium": "Tamil",
      "exam_type": "Quarterly",
      "resource_type": "Important-Q",
      "year": 2026,
      "pages": 9,
      "price_tier": "free",
      "price_inr": 0,
      "marks_pattern": "பகுதி I, II, III, IV - 100 மதிப்பெண்கள்",
      "file_url": "s3://ravis-tuition/10-tamil-2026.pdf"
    },
    {
      "id": "11-maths-english-halfyearlymodel-2024",
      "title_en": "11th Maths Half-Yearly Model Paper 2024",
      "title_ta": "11 ஆம் வகுப்பு கணிதம் அரையாண்டு மாதிரி 2024",
      "class": 11,
      "subject": "maths",
      "medium": "English",
      "exam_type": "Half-Yearly",
      "resource_type": "Model Papers",
      "year": 2024,
      "pages": 8,
      "price_tier": "free",
      "price_inr": 0,
      "marks_pattern": "Part I 20×1=20 · Part II 7×2=14 · Part III 7×3=21 · Part IV 7×5=35 = 90 marks",
      "file_url": "s3://ravis-tuition/11-maths-2024.pdf"
    },
    {
      "id": "09-maths-english-quarterlyimpq-2026",
      "title_en": "9th Maths Quarterly Important Questions 2026 - FREE",
      "title_ta": "9 ஆம் வகுப்பு கணிதம் முக்கிய வினாக்கள் 2026",
      "class": 9,
      "subject": "maths",
      "medium": "English",
      "exam_type": "Quarterly",
      "resource_type": "Important-Q",
      "year": 2026,
      "pages": 8,
      "price_tier": "free",
      "price_inr": 0,
      "marks_pattern": "100 marks, 3 hrs - Samacheer blueprint",
      "file_url": "s3://ravis-tuition/9-maths-2026.pdf",
      "is_free_lead_magnet": true
    },
    {
      "id": "08-science-english-quarterlynotes-2026",
      "title_en": "8th Science Quarterly Notes 2026 - FREE",
      "title_ta": "8 ஆம் வகுப்பு அறிவியல் குறிப்புகள் 2026",
      "class": 8,
      "subject": "science",
      "medium": "English",
      "exam_type": "Quarterly",
      "resource_type": "Notes",
      "year": 2026,
      "pages": 22,
      "price_tier": "free",
      "price_inr": 0,
      "marks_pattern": "Chapter-wise key points",
      "file_url": "s3://ravis-tuition/8-science-2026.pdf",
      "is_free_lead_magnet": true
    },
    {
      "id": "10-english-english-quarterlymodel-2026",
      "title_en": "10th English Quarterly Model Paper 2026",
      "title_ta": "10 ஆம் வகுப்பு ஆங்கிலம் மாதிரி 2026",
      "class": 10,
      "subject": "english",
      "medium": "English",
      "exam_type": "Quarterly",
      "resource_type": "Model Papers",
      "year": 2026,
      "pages": 7,
      "price_tier": "free",
      "price_inr": 0,
      "marks_pattern": "Section I-V, 100 marks",
      "file_url": "s3://ravis-tuition/10-english-2026.pdf"
    },
    {
      "id": "12-biology-english-quarterlyimpq-2026",
      "title_en": "12th Biology Quarterly Important Questions 2026 - Botany + Zoology",
      "title_ta": "12 ஆம் வகுப்பு உயிரியல் முக்கிய வினாக்கள் 2026",
      "class": 12,
      "subject": "biology",
      "medium": "English",
      "exam_type": "Quarterly",
      "resource_type": "Important-Q",
      "year": 2026,
      "pages": 18,
      "price_tier": "free",
      "price_inr": 0,
      "marks_pattern": "Botany 35 + Zoology 35 = 70 marks",
      "file_url": "s3://ravis-tuition/12-biology-2026.pdf"
    },
    {
      "id": "11-physics-english-quarterlynotes-2026",
      "title_en": "11th Physics Quarterly Notes 2026 - Full Portions",
      "title_ta": "11 ஆம் வகுப்பு இயற்பியல் குறிப்புகள் 2026",
      "class": 11,
      "subject": "physics",
      "medium": "English",
      "exam_type": "Quarterly",
      "resource_type": "Notes",
      "year": 2026,
      "pages": 32,
      "price_tier": "free",
      "price_inr": 0,
      "marks_pattern": "Unit 1-5 consolidated",
      "file_url": "s3://ravis-tuition/11-physics-2026.pdf"
    },
    {
      "id": "10-social-english-quarterlyimpq-2026",
      "title_en": "10th Social Science Quarterly Important Q 2026 - History + Geo",
      "title_ta": "10 ஆம் வகுப்பு சமூக அறிவியல் முக்கிய வினாக்கள் 2026",
      "class": 10,
      "subject": "social",
      "medium": "English",
      "exam_type": "Quarterly",
      "resource_type": "Important-Q",
      "year": 2026,
      "pages": 15,
      "price_tier": "free",
      "price_inr": 0,
      "marks_pattern": "History 40 + Geography 20 + Civics 20 + Eco 20 = 100",
      "file_url": "s3://ravis-tuition/10-social-2026.pdf"
    },
    {
      "id": "12-maths-english-quarterlyimpq-2026",
      "title_en": "12th Maths Quarterly Important Questions 2026",
      "title_ta": "12 ஆம் வகுப்பு கணிதம் காலாண்டு முக்கிய வினாக்கள் 2026",
      "class": 12,
      "subject": "maths",
      "medium": "English",
      "exam_type": "Quarterly",
      "resource_type": "Important-Q",
      "year": 2026,
      "pages": 13,
      "price_tier": "free",
      "price_inr": 0,
      "marks_pattern": "Part I 20×1=20 · Part II 7×2=14 · Part III 7×3=21 · Part IV 7×5=35 = 90 marks",
      "file_url": "s3://ravis-tuition/12-maths-2026.pdf"
    }
  ]
};
